language: node_js
node_js:
    - 0.8
notifications:
    email: false
    hipchat: 33d0319e384ba2d38a29b40c07bfdd@Alerts
services:
    - redis-server
    - mysql
branches:
    except:
        - production
before_script:
    - cp test/resources/config.travis.json test/resources/config.json
