CREATE TABLE IF NOT EXISTS Apps (`app` VARCHAR(255) PRIMARY KEY, secret VARCHAR(255), apikeys TEXT, notes TEXT, `cat` TIMESTAMP  NULL  DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS Grants (`code` VARCHAR(255) PRIMARY KEY, account VARCHAR(255), app VARCHAR(255), `cat` TIMESTAMP  NULL  DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS Accounts (id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY, account VARCHAR(255), app VARCHAR(255), profile VARCHAR(255), `cat` TIMESTAMP  NULL  DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS Profiles (id VARCHAR(255) PRIMARY KEY, service VARCHAR(32), auth TEXT, config TEXT, `cat` TIMESTAMP  NULL  DEFAULT CURRENT_TIMESTAMP);
